name: cess-multiminer
services:
  miner1:
    container_name: miner1
    image: 'cesslab/cess-miner:devnet'
    network_mode: host
    restart: always
    volumes:
      - '/mnt/cess_storage1/miner:/opt/miner'
      - '/mnt/cess_storage1/storage:/opt/miner-disk'
    command:
      - run
      - '-c'
      - /opt/miner/config.yaml
    logging:
      driver: json-file
      options:
        max-size: 500m
    healthcheck:
      test: ["CMD", "nc", "-zv", "127.0.0.1", "15001"]
      interval: 1m
      timeout: 10s
      retries: 3
  miner2:
    container_name: miner2
    image: 'cesslab/cess-miner:devnet'
    network_mode: host
    restart: always
    volumes:
      - '/mnt/cess_storage2/miner:/opt/miner'
      - '/mnt/cess_storage2/storage:/opt/miner-disk'
    command:
      - run
      - '-c'
      - /opt/miner/config.yaml
    logging:
      driver: json-file
      options:
        max-size: 500m
    healthcheck:
      test: ["CMD", "nc", "-zv", "127.0.0.1", "15002"]
      interval: 1m
      timeout: 10s
      retries: 3
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: host
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command:
      - '--cleanup'
      - '--interval'
      - '300'
      - '--enable-lifecycle-hooks'
      - chain
      - miner1
      - miner2
      - autoheal
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '7'
  watchdog:
    image: cesslab/watchdog
    container_name: watchdog
    network_mode: host
    restart: always
    volumes:
      - '/opt/monitor/config.yaml:/opt/monitor/config.yaml'
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '7'
  watchdog-web:
    image: cesslab/watchdog-web
    container_name: watchdog-web
    network_mode: host
    restart: always
    environment:
      - API_URL=http://34.136.50.49:13080
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '7'
  autoheal:
    image: 'willfarrell/autoheal:latest'
    container_name: autoheal
    network_mode: host
    tty: true
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - '- AUTOHEAL_CONTAINER_LABEL=all'
      - '- AUTOHEAL_INTERVAL=60'
      - '- AUTOHEAL_START_PERIOD=180'
      - '- AUTOHEAL_DEFAULT_STOP_TIMEOUT=10'