# external: run with 0.0.0.0 or 127.0.0.1
external: true
# watchdog server listen http port at: 13081
port: 13081
# the interval of query data from chain for each miner, 30 <= scrapeInterval <= 300
scrapeInterval: 60
hosts:
  - ip: 127.0.0.1
    # make sure docker daemon listen at 2375: https://docs.docker.com/config/daemon/remote-access/
    port: 2375
  # Configure remote access for Docker daemon must use tls to make sure mnemonic safe when do network transmission
  # set ca/crt/key path if the ip no belongs to [ 127.x, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 ]
  - ip: 1.1.1.1
    # make sure docker daemon tls listen at 2376: https://docs.docker.com/engine/security/protect-access/
    port: 2376
    ca_path: /opt/cess/watchdog/tls/1.1.1.1-ca.pem
    cert_path: /opt/cess/watchdog/tls/1.1.1.1-cert.pem
    key_path: /opt/cess/watchdog/tls/1.1.1.1-key.pem
alert:
  # enable alert or not
  enable: false
  webhook:
    - https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX
    - https://discordapp.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  email:
    smtp_endpoint: smtp.example.com
    smtp_port: 80
    smtp_account: myservice@cess.cloud
    smtp_password: my_pwd
    receive_addr:
      - example1@gmail.com
      - example2@outlook.com